<?xml version="1.0" ?>
<robot name="filburbot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="wheel_radius" value="0.0325"/>
  <xacro:property name="wheel_separation" value="0.155"/>
  <xacro:property name="wheel_thickness" value="0.025"/>

  <link name="base_link"></link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="chassis" />
  </joint>

  <link name="chassis">
    <visual>
      <geometry>
        <box size="${wheel_separation - wheel_thickness} 0.16 0.17"/>
      </geometry>
    </visual>
  </link>

  <link name="neato_laser">
    <visual>
      <geometry>
        <cylinder length="0.02" radius="0.04"/>
      </geometry>
    </visual>
  </link>

  <joint name="neato_laser_joint" type="fixed">
    <origin xyz="0.01 0 ${(0.17 + 0.02)/2}" rpy="0 0 0" />
    <parent link="chassis"/>
    <child link="neato_laser" />
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="0 -${(wheel_separation + wheel_thickness)/2} ${-0.17/2 + 0.02}" rpy="1.5708 0 0" />
    <axis xyz="0 0 -1"/>
    <parent link="chassis"/>
    <child link="left_wheel" />
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
    </visual>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="0 ${(wheel_separation + wheel_thickness)/2} ${-0.17/2 + 0.02}" rpy="1.5708 0 0" />
    <axis xyz="0 0 -1"/>
    <parent link="chassis"/>
    <child link="right_wheel" />
  </joint>
</robot>
